#!/bin/bash

# Title:	insmoji
# By: 		OfficialKingJulian
# Tag Added:	07-03-2020
# Description:  Insert an emoji with rofi

# change '.*' for letter*
printf $(grep "${1}" emoji | sed -e 's/ //g;s/f.*//g')
