#!/bin/bash

# Title:	gcbr
# By: 		OfficialKingJulian
# Tag Added:	15-02-2020
# Description:  Updates the custom Google Calendar Module for Polybar

while true ; do
  python ${HOME}/.config/polybar/cal/nextevent.py > ${HOME}/.config/polybar/cal/output.txt
  sleep 60
done
