#!/bin/bash

# Title:	.bin/wmreload
# By: 		kingjuliando
# Tag Added:	10-06-2020
# Description:  Reloads bspwm and sxhkd

# bspwm
  /home/ju/.config/bspwm/bspwmrc

# sxhkd
  #/baskerville/sxhkd/issues/94
  pkill -USR1 -x sxhkd
