#!/bin/sh

sxhkd &

# General
  bspc monitor -d      
  bspc config border_width         1
  bspc config window_gap           30
  bspc config split_ratio          0.52
  bspc config borderless_monocle   true
  bspc config gapless_monocle      true

# Borders
  bspc config active_border_color \#EA526F
  bspc config normal_border_color \#4CBAB800

# Window Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
  bspc rule -a Firefox desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
  bspc rule -a hirimain state=floating

# Run These Please
  runloc="/home/ju/.config/bspwm/bin/"
  # Polybar
    ${runloc}/poly &
  # Polybar Cal Updater
#   pkill gcbr &
#   ${runloc}/gcbr &
  # Compton
    picom -b &
  # Background
    pkill bg &
    ${runloc}/bg &
  # Protonmail Bridge
#   screen -dmS protonmailbridge.start /usr/bin/protonmail-bridge -c &
  # Battery Notification Tool
    pkill bat
    ${runloc}/bat
